theme_spec: scripts/spt6_2018_theme_specification.R

figure0:
    height: 2
    width: 7

figure1:
    data_path: ../../intragenic/spt6-data-integration/browser-shots/TEF1/TEF1_TSS-seq-sense.tsv.gz
    height: 3.3
    width: 7

figure2:
    annotation: ../../intragenic/genomefiles_cerevisiae/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed
    tss_sense: ../../intragenic/tss-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/spikenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-tss-seq-spikenorm-SENSE.tsv.gz
    tss_antisense: ../../intragenic/tss-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/spikenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-tss-seq-spikenorm-ANTISENSE.tsv.gz
    height: 9.55
    width: 17.4

figure3:
    sense_tfiib_data: ../../intragenic/chipnexus-tfiib/datavis/rhee2012-TATAboxes-cleaned/libsizenorm/rhee2012-TATAboxes-cleaned-allsamples-allannotations-tfiib-chipnexus-libsizenorm-SENSE.tsv.gz
    antisense_tfiib_data: ../../intragenic/chipnexus-tfiib/datavis/rhee2012-TATAboxes-cleaned/libsizenorm/rhee2012-TATAboxes-cleaned-allsamples-allannotations-tfiib-chipnexus-libsizenorm-ANTISENSE.tsv.gz
    height: 4
    width: 6

figure4:
    tfiib_data: ../../intragenic/chipnexus-tfiib/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/libsizenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-tfiib-chipnexus-libsizenorm-protection.tsv.gz
    annotation: ../../intragenic/genomefiles_cerevisiae/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed
    height: 9.55
    width: 8.7

figure5:
    genic: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/genic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-genic-all.tsv
    intragenic: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-all.tsv
    antisense: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/antisense/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-antisense-all.tsv
    intergenic: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intergenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intergenic-all.tsv
    height: 4
    width: 8.5

figure6:
    tss_genic: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/genic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-genic-all.tsv
    tss_intragenic: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-all.tsv
    tss_antisense: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/antisense/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-antisense-all.tsv
    tss_intergenic: ../../intragenic/tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intergenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intergenic-all.tsv
    height: 5
    width: 8.5

figure7:
    genic: ../../intragenic/tss-v-tfiib-nexus/diff_binding/spt6-1004-37C-v-WT-37C-tfiib-window-results-genic.tsv
    intragenic: ../../intragenic/tss-v-tfiib-nexus/diff_binding/spt6-1004-37C-v-WT-37C-tfiib-window-results-intragenic.tsv
    antisense: ../../intragenic/tss-v-tfiib-nexus/diff_binding/spt6-1004-37C-v-WT-37C-tfiib-window-results-antisense.tsv
    width: 17.4
    height: 4.5

figure8:
    tfiib_data: ../../intragenic/spt6-data-integration/datavis/spreading-ssa4/spreading-ssa4_TFIIB-ChIP-nexus-protection.tsv.gz
    height: 6
    width: 11

figure9:
    mnase_data: ../../intragenic/viktorovskaya-mnase-seq/datavis/verified-transcripts-nonoverlapping-plusonenuc/spikenorm/verified-transcripts-nonoverlapping-plusonenuc-allsamples-allannotations-midpoint-spikenorm.tsv.gz
    annotation: ../../intragenic/genomefiles_cerevisiae/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping-WT-NETseq-sort-plusone-nucdyad.bed
    height: 5.5
    width: 8.5

figure10:
    wt_mnase_quant: ../../intragenic/viktorovskaya-mnase-seq/nucleosome_quantification/spt6-1004-37C-v-WT-37C/spikenorm/pooled/nucleosome_quantification_data_WT-37C.Fnor.smooth.positions.xls
    spt6_mnase_quant: ../../intragenic/viktorovskaya-mnase-seq/nucleosome_quantification/spt6-1004-37C-v-WT-37C/spikenorm/pooled/nucleosome_quantification_data_spt6-1004-37C.Fnor.smooth.positions.xls
    height: 5.5
    width: 8.5

figure11:
    netseq_data: ../../intragenic/murawska-net-seq/datavis/verified-transcripts-nonoverlapping-TSS-NETseq-sort/libsizenorm/verified-transcripts-nonoverlapping-TSS-NETseq-sort-allsamples-allannotations-libsizenorm-5end-SENSE.tsv.gz
    mnase_data: ../../intragenic/viktorovskaya-mnase-seq/datavis/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort/spikenorm/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort-allsamples-allannotations-midpoint-spikenorm.tsv.gz
    quant_data: ../../intragenic/viktorovskaya-mnase-seq/nucleosome_quantification/regions/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort/spikenorm/spt6-1004-37C-v-WT-37C/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort-allannotations-integrated-spikenorm.tsv
    annotation: ../../intragenic/genomefiles_cerevisiae/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping-WT-NETseq-sort-plusone-nucdyad.bed
    height: 11.5
    width: 17.4

figure12:
    mnase_data: ../../intragenic/spt6-data-integration/datavis/spt6-induced-intragenic-TSSs-MNase-clusters-v-genic/spt6-induced-intragenic-TSSs-MNase-clusters-v-genic_MNase-seq.tsv.gz
    gc_data: ../../intragenic/spt6-data-integration/datavis/spt6-induced-intragenic-TSSs-MNase-clusters-v-genic/spt6-induced-intragenic-TSSs-MNase-clusters-v-genic_GC-pct.tsv.gz
    height: 8
    width: 17.4

figure13:
    data_paths:
        - ../../intragenic/tss-seq/seq_logos/spt6-1004-37C/spt6-1004-37C-genic-seqlogo.tsv
        - ../../intragenic/tss-seq/seq_logos/spt6-1004-37C/spt6-1004-37C-intragenic-seqlogo.tsv
    height: 4
    width: 8.7

figure14:
    tata_genic: ../../intragenic/motif_analysis_tata/comparisons/all-genic-v-random/all-genic-v-random_condition_allFIMOresults.tsv.gz
    tata_intragenic: ../../intragenic/motif_analysis_tata/comparisons/all-intragenic-v-random/all-intragenic-v-random_condition_allFIMOresults.tsv.gz
    tata_random: ../../intragenic/motif_analysis_tata/comparisons/all-intragenic-v-random/all-intragenic-v-random_control_allFIMOresults.tsv.gz
    height: 4
    width: 8.6

stress_figure1:
    tfiib_data: ../../intragenic/chipnexus-tfiib/datavis/genes-with-stress-induced-intra-peaks/libsizenorm/genes-with-stress-induced-intra-peaks-allsamples-allannotations-tfiib-chipnexus-libsizenorm-protection.tsv.gz
    height: 12
    width: 17.4

spt5_figure1:
    netseq_data: ../../spt5/spt5-data-integration/datavis/coding-transcripts-nonoverlapping-scaled/coding-transcripts-nonoverlapping-scaled_NET-seq-sense.tsv.gz
    annotation: ../../spt5/genome/annotations/S_pombe_codingtranscripts-adjustedTSS-nonoverlapping.bed
    height: 4.5
    width: 8.5

spt5_figure2:
    rnaseq_data: ../../spt5/rna-seq/datavis/coding-transcripts-nonoverlapping-slopR300-TSS/libsizenorm/coding-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-libsizenorm-wholeread-ANTISENSE.tsv.gz
    annotation: ../../spt5/genome/annotations/S_pombe_codingtranscripts-adjustedTSS-nonoverlapping-slopR300.bed
    height: 8.5
    width: 11

spt5_figure3:
    tssseq_data: ../../spt5/spt5-data-integration/datavis/transcripts-w-anti-antidistsort/transcripts-w-anti-antidistsort_TSS-seq-antisense.tsv.gz
    rnaseq_data: ../../spt5/spt5-data-integration/datavis/transcripts-w-anti-antidistsort/transcripts-w-anti-antidistsort_RNA-seq-antisense.tsv.gz
    netseq_data: ../../spt5/spt5-data-integration/datavis/transcripts-w-anti-antidistsort/transcripts-w-anti-antidistsort_NET-seq-antisense.tsv.gz
    width: 17.4
    height: 10.25

spt5_figure4:
    mnase_data: ../../spt5/mnase-seq/datavis/nonoverlapping-genes-plusonenuc/libsizenorm/nonoverlapping-genes-plusonenuc-allsamples-allannotations-midpoint-libsizenorm.tsv.gz
    width: 8.7
    height: 5

spt5_figure5:
    mnase_data: ../../spt5/spt5-data-integration/datavis/antisense-tss/antisense-tss_MNase-seq.tsv.gz
    gc_data: ../../spt5/spt5-data-integration/datavis/antisense-tss/antisense-tss_GC-pct.tsv.gz
    width: 8.7
    height: 6

spt5_figure6:
    wt_mnase_quant: ../../spt5/mnase-seq/nucleosome_quantification/depleted-v-non-depleted/libsizenorm/pooled/nucleosome_quantification_data_non-depleted.Fnor.smooth.positions.xls
    spt5_mnase_quant: ../../spt5/mnase-seq/nucleosome_quantification/depleted-v-non-depleted/libsizenorm/pooled/nucleosome_quantification_data_depleted.Fnor.smooth.positions.xls
    height: 4.25
    width: 8.5

presentation_figure0:
    data_path: ../../intragenic/spt6-data-integration/browser-shots/MVD1/MVD1_all-assays.tsv.gz
    height: 9
    width: 16

presentation_figure1:
    height: 9
    width: 16

presentation_figure2:
    height: 9
    width: 16

presentation_figure3:
    height: 9
    width: 16

presentation_figure4:
    height: 6.5
    width: 16

presentation_figure5:
    height: 8
    width: 8

presentation_figure6:
    height: 6
    width: 8

presentation_figure7:
    height: 6
    width: 8

presentation_figure8:
    height: 8
    width: 8

presentation_figure9:
    height: 7
    width: 16

presentation_figure10:
    height: 9
    width: 16

presentation_figure11:
    height: 9
    width: 16

presentation_figure12:
    height: 7
    width: 16

presentation_figure13:
    height: 7
    width: 16
