theme_spec: scripts/spt6_2018_theme_specification.R

figure_one:
    data_path: ../../intragenic/spt6-data-integration/browser-shots/TEF1/TEF1_TSS-seq-sense.tsv.gz
    height: 5
    width: 8

figure_two:
    annotation: ../../intragenic/genomefiles_cerevisiae/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed
    tss_sense: ../../intragenic/tss-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/spikenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-tss-seq-spikenorm-SENSE.tsv.gz
    tss_antisense: ../../intragenic/tss-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/spikenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-tss-seq-spikenorm-ANTISENSE.tsv.gz
    height: 10
    width: 17.4

figure_three:
    sense_tfiib_data: ../../chipnexus-tfiib/datavis/rhee2012-TATAboxes-cleaned/libsizenorm/rhee2012-TATAboxes-cleaned-allsamples-allannotations-tfiib-chipnexus-libsizenorm-SENSE.tsv.gz
    antisense_tfiib_data: ../../chipnexus-tfiib/datavis/rhee2012-TATAboxes-cleaned/libsizenorm/rhee2012-TATAboxes-cleaned-allsamples-allannotations-tfiib-chipnexus-libsizenorm-ANTISENSE.tsv.gz
    height: 4
    width: 5
